### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by DaniloAgostinho** [ericdouglas/spaced-dictionary#1]
This repository will be to learn English?

**Comment by ericdouglas** [comment]
Hi @DaniloAgostinho ! No, man. This is a repository to an application that I'll create.

You can see some resources to learn English in [this](https://github.com/ericdouglas/esl) repository.

:smile:

**Comment by DaniloAgostinho** [comment]
@ericdouglas cool, this repository, that was my idea, I created my own repository but I confess that I take a onyour also analyzed.

and how is your English? This methodology is being efficient?

**Comment by ericdouglas** [comment]
@DaniloAgostinho I've not reached an ideal methodology yet... But I'll focus initially to improve conversation and vocabulary. 

After it, I'll look more deeply in grammar.

**Comment by DaniloAgostinho** [comment]
can count on me to train conversation, can be through hangouts.

**Comment by ericdouglas** [comment]
@DaniloAgostinho great! Send an email to me, see in my profile you what it's.
